students = [
    {"id": 1, "name": "Alice Johnson", "age": 20, "grade": "A", "major": "Computer Science", "gpa": 3.9},
    {"id": 2, "name": "Bob Martinez", "age": 22, "grade": "B", "major": "Mathematics", "gpa": 3.2},
    {"id": 3, "name": "Clara Liu", "age": 19, "grade": "A", "major": "Physics", "gpa": 3.8},
    {"id": 4, "name": "David Okafor", "age": 21, "grade": "C", "major": "History", "gpa": 2.7},
    {"id": 5, "name": "Eva Rossi", "age": 23, "grade": "B", "major": "Biology", "gpa": 3.4},
    {"id": 6, "name": "Felix Huang", "age": 20, "grade": "A", "major": "Computer Science", "gpa": 3.7},
    {"id": 7, "name": "Grace Patel", "age": 22, "grade": "B", "major": "Chemistry", "gpa": 3.1},
    {"id": 8, "name": "Henry Dubois", "age": 21, "grade": "C", "major": "Economics", "gpa": 2.5},
    {"id": 9, "name": "Isla Nakamura", "age": 19, "grade": "A", "major": "Engineering", "gpa": 3.95},
    {"id": 10, "name": "James Owens", "age": 24, "grade": "B", "major": "Philosophy", "gpa": 3.3},
    {"id": 11, "name": "Kira Svensson", "age": 20, "grade": "A", "major": "Computer Science", "gpa": 3.6},
    {"id": 12, "name": "Luca Bianchi", "age": 22, "grade": "C", "major": "Art History", "gpa": 2.8},
    {"id": 13, "name": "Maya Nkosi", "age": 21, "grade": "B", "major": "Psychology", "gpa": 3.0},
    {"id": 14, "name": "Noah Kim", "age": 23, "grade": "A", "major": "Mathematics", "gpa": 3.85},
    {"id": 15, "name": "Olivia Ferreira", "age": 20, "grade": "B", "major": "Biology", "gpa": 3.2},
    {"id": 16, "name": "Paul Mensah", "age": 22, "grade": "C", "major": "Sociology", "gpa": 2.6},
    {"id": 17, "name": "Quinn Torres", "age": 19, "grade": "A", "major": "Engineering", "gpa": 3.75},
    {"id": 18, "name": "Rosa Andersen", "age": 21, "grade": "B", "major": "Physics", "gpa": 3.15},
    {"id": 19, "name": "Sam Yilmaz", "age": 20, "grade": "A", "major": "Computer Science", "gpa": 3.65},
    {"id": 20, "name": "Tara Obi", "age": 23, "grade": "C", "major": "Economics", "gpa": 2.9},
]